### ISSUE TITLE
关于主控

### ISSUE THREAD

**Issue by a12t37** [blackbox114/Blacky#21]
请问主控使用的是raspberryPi4_4G吗？
操作系统是什么版本的？
性能如何，后续使用ROS系统需要更换主控吗？

**Comment by a12t37** [comment]
> 
> 
> 请问主控使用的是raspberryPi4_4G吗？
> 操作系统是什么版本的？
> 性能如何，后续使用ROS系统需要更换主控吗？

**Comment by blackbox114** [comment]
稍后我会上传一份我目前使用的镜像。目前使用这份镜像能够正常运行，其他的版本都需要修改一些设置。

 关于性能，目前树莓派4b的性能实际上已经足够，同时在处理ROS服务也是可以的，不过请将大部分运算放到你的上位机上。仅用树莓派作为ROS的某一终端执行操作和采集数据

如果不需要视觉的话会考虑制作树莓派zero版本，可以进一步降低成本

**Comment by blackbox114** [comment]
> 请问主控使用的是raspberryPi4_4G吗？
> 操作系统是什么版本的？
> 性能如何，后续使用ROS系统需要更换主控吗？
请使用这个镜像在树莓派4上构建  https://github.com/blackbox114/Blacky/tree/div/rpisystem

**Comment by blackbox114** [comment]
> 请问主控使用的是raspberryPi4_4G吗？
> 操作系统是什么版本的？
> 性能如何，后续使用ROS系统需要更换主控吗？

请访问 https://github.com/blackbox114/Blacky/tree/div/rpisystem 获取镜像，并在树莓派4上构建系统

**Comment by blackbox114** [comment]
烧录镜像已经放在[此处]https://github.com/blackbox114/Blacky/tree/master/rpiOS) 。实际上测试发现直接下载2019-09-26-raspbian-buster-lite也是可以使用的
