### ISSUE TITLE
关于打印件

### ISSUE THREAD

**Issue by zhansheng** [blackbox114/Blacky#24]
你好，打印件你是在哪里打印的，方便留个联系方式吗？

**Comment by blackbox114** [comment]
打印件我是在淘宝上找到的一家店，搜“未来工厂”可以搜到。我这里的打印件重量低于210g，所以当时打印没收钱，只收了邮费，你可以去看看未来工厂还有没有这样的活动

**Comment by zhansheng** [comment]
好的，谢谢

**Comment by blackbox114** [comment]
不客气。另外，打印件适配的是8mm碳纤维管或铝管，长度300mm
