### ISSUE TITLE
Outdated PCB link to easyeda

### ISSUE THREAD

**Issue by LaryLee** [blackbox114/Blacky#30]
Hi,
it seems like the link to easyeda.com is only for V2 of the PCB.
Could you please supply the link to v3, as I would like to make some changes?

Thank you!

**Comment by blackbox114** [comment]
Hi,
V3 of the PCB&nbsp; has been uploaded.
Thanks for your email, I almost forgot that I should upload a new file.


This is the new link.&nbsp;&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Mon, May 24, 2021 10:04 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: &nbsp;[blackbox114/Blacky] Outdated PCB link to easyeda (#30)

&nbsp;



 
Hi,
 it seems like the link to easyeda.com is only for V2 of the PCB.
 Could you please supply the link to v3, as I would like to make some changes?
 
Thank you!

**Comment by LaryLee** [comment]
Thank you!
