### ISSUE TITLE
Provide carbon fibre rod length

### ISSUE THREAD

**Issue by LaryLee** [blackbox114/Blacky#31]
Hi,
could you please provide the length of the carbon fibre rod?

Thank you :)

**Comment by blackbox114** [comment]
Hello！


The length of the carbon fiber rod is 30.


GoodLuck！


&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Fri, Jun 4, 2021 03:39 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: &nbsp;[blackbox114/Blacky] Provide carbon fibre rod length (#31)

&nbsp;



 
Hi,
 could you please provide the length of the carbon fibre rod?
 
Thank you :)

**Comment by LaryLee** [comment]
Thank you!
